---
- name: Install\Upgrade Docker Engine
  hosts: 
    - backend
    - frontend
  tags: all-check  #удобно для вызова из ansible-playbook -i --tags frontend
  roles:
    - preparing

- name: Install backend of Pelmennaya-Store
  tags: backend #удобно для вызова из ansible-playbook -i --tags frontend
  hosts: backend

  roles: 
    - backend

- name: Install frontend of Pelmennaya-Store
  tags: frontend #удобно для вызова из ansible-playbook -i --tags frontend
  hosts: frontend
  roles: 
    - frontend
