---
- name: Install\Upgrade Docker Engine
  hosts: 
    - backend
    - frontend
  tags: all-check  #удобно для вызова из ansible-playbook -i --tags all-check
  roles:
    - preparing

- name: Install\Upgrade Prometheus\Grafana
  hosts: 
    - backend
    - frontend
  tags: monitoring  #удобно для вызова из ansible-playbook -i --tags monitoring
  roles:
    - monitoring

- name: Install backend of Pelmennaya-Store
  tags: backend #удобно для вызова из ansible-playbook -i --tags backend
  hosts: backend

  roles: 
    - backend

- name: Install frontend of Pelmennaya-Store
  tags: frontend #удобно для вызова из ansible-playbook -i --tags frontend
  hosts: frontend
  roles: 
    - frontend
