stages:
  - prepare
  - build
  - test
  - release-binary
  - docker-gen-image
  - create-auth
  - create-machine
  - connect-to-machine
variables:
  NODE_VERSION: "${NODE_VERSION}"
  APP_NAME: pelmennaya-frontend
  MAJOR: "1"
  MINOR: "0"
  PATCH: "2"
  TF_VERS: "1.9.6"
  TF_VAR_zone1: "ru-central1-a"
  TF_VAR_vm_name: "pelmennaya-vm"
  TF_VAR_ssh_public_keys: "qqq"
  TF_CLI_CONFIG_FILE: "${CI_PROJECT_DIR}/repo/terraform/.terraformrc"
cache:
  paths:
    - frontend/dist/ # передаю кеш в другие задачи

generate-version:
  stage: prepare
  script:
    - |
     if [[ -n "$CI_COMMIT_TAG" ]]; then
        # Релизная версия из тега (v1.2.3 → 1.2.3)
        VERSION=$(echo "$CI_COMMIT_TAG" | sed 's/^r//')  # Удаляем 'v' при наличии
        DIR_BRANCH=release
      elif [[ "$CI_COMMIT_BRANCH" == "main" ]]; then
      # main без тега (например, ручной запуск пайплайна)
        VERSION="${MAJOR}.${MINOR}.${PATCH}"
        DIR_BRANCH=release
      elif [[ "$CI_COMMIT_BRANCH" == "develop" ]]; then
        # Develop версия (1.0.1-dev+commit)
        VERSION="${MAJOR}.${MINOR}.$(($PATCH + 1))-dev_$(echo "$CI_COMMIT_SHA" | cut -c1-8)"
        DIR_BRANCH=develop        
      elif [[ "$CI_COMMIT_BRANCH" =~ ^feature/ ]]; then
        # Feature версия (1.0.1-feat-branchname+commit)
        BRANCH_NAME=$(echo "$CI_COMMIT_REF_SLUG" | sed 's/feature-/feat-/')
        VERSION="${MAJOR}.${MINOR}.$(($PATCH + 1))-${BRANCH_NAME}_$(echo "$CI_COMMIT_SHA" | cut -c1-8)"
        DIR_BRANCH=feature      
      elif [[ "$CI_COMMIT_BRANCH" =~ ^release/ ]]; then
        # RC версия (1.0.1-rc.1+commit)
        RC_NUM=$(echo "$CI_COMMIT_REF_NAME" | awk -F'[-.]' '{print $2}')
        VERSION="${MAJOR}.${MINOR}.${PATCH}-rc.${RC_NUM}_$(echo "$CI_COMMIT_SHA" | cut -c1-8)"
        DIR_BRANCH=release-candidate            
      else
        # Fallback версия
        VERSION="${MAJOR}.${MINOR}.${PATCH}-unknown_$(echo "$CI_COMMIT_SHA" | cut -c1-8)"
        DIR_BRANCH=unknown
      fi
    - echo "VERSION=${VERSION}" > build.env
    - echo "FRONTEND_VERSION=${VERSION}" >> build.env
    - echo "DIR_BRANCH=${DIR_BRANCH}" >> build.env
  artifacts:
    reports:
      dotenv: build.env


build-frontend-code-job:
  stage: build
  image:
    name: node:${NODE_VERSION}
  script:
    - cd frontend
    - npm install
    - > 
      NODE_OPTIONS="--openssl-legacy-provider" 
      NODE_ENV="production" 
      VUE_APP_API_URL="/api" 
      npm run build
  needs:
    - generate-version      

sonarqube-check-frontend:
  stage: test
  image:
    name: sonarsource/sonar-scanner-cli:latest
    entrypoint: [""]
  variables:
    SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"  # Defines the location of the analysis task cache
    GIT_DEPTH: "0"  # Tells git to fetch all the branches of the project, required by the analysis task
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  script:
    - cd frontend/
    - > 
      sonar-scanner -X   
      ${SONAR_PROJECT_KEY_FRONT} 
      ${SONARQUBE_DIR} 
      ${SONARQUBE_URL} 
      ${SONAR_LOGIN} 
      -Dsonar.qualitygate.wait=true
  allow_failure: false
#  rules:
#    - if: $CI_COMMIT_REF_NAME == 'main' || $CI_PIPELINE_SOURCE == 'merge_request_event' || $CI_COMMIT_REF_NAME =~ /^feature\/.+/
  needs:
    - build-frontend-code-job  

upload-binary-pelmennaya:
  stage: release-binary
  script:
    - tar czvf ${APP_NAME}-${VERSION}.tar.gz frontend/dist
    - >
      curl -v -u "${NEXUS_REPO_USER}:${NEXUS_REPO_PASS}"
      --upload-file ${APP_NAME}-${VERSION}.tar.gz
      ${NEXUS_REPO_URL}/repository/${NEXUS_REPO_FRONTEND_NAME}/${DIR_BRANCH}/${APP_NAME}-${VERSION}.tar.gz
  needs:
    - job: sonarqube-check-frontend
      artifacts: true
    - job: generate-version
      artifacts: true

build-docker-frontend-code-job:
  stage: docker-gen-image
  image:
    name: gcr.io/kaniko-project/executor:v1.9.0-debug
    entrypoint: [""]
  # переменные CI_REGISTRY_USER, CI_REGISTRY_PASSWORD, CI_REGISTRY генерятся Гитлабом, их задавать не надо
  script:
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}/frontend"
      --dockerfile "${CI_PROJECT_DIR}/frontend/Dockerfile"
      --destination "${CI_REGISTRY_IMAGE}/${APP_NAME}"
      --build-arg "CRED_NEXUS=${NEXUS_REPO_USER}:${NEXUS_REPO_PASS}"
      --build-arg "URL_TO_DOWNLOAD=${NEXUS_REPO_URL}/repository/${NEXUS_REPO_FRONTEND_NAME}/${DIR_BRANCH}"
      --build-arg "APP_NAME=${APP_NAME}-${VERSION}"
      --cache=true
  needs:
    - upload-binary-pelmennaya
    - generate-version


release-frontend-docker-image:
  stage: docker-gen-image
  variables:
    GIT_STRATEGY: none
  image:
    name: gcr.io/go-containerregistry/crane:debug
    entrypoint: [ "" ]
  cache: [ ]
  before_script:
    - crane auth login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - crane tag $CI_REGISTRY_IMAGE/$APP_NAME $VERSION
  needs:
    - build-docker-frontend-code-job
    - generate-version

create-auth-and-bucket:
  image: alpine:3.18
  stage: create-auth
  before_script:
      - apk add bash curl unzip envsubst unzip jq
      - curl -LO "https://hashicorp-releases.yandexcloud.net/terraform/${TF_VERS}/terraform_${TF_VERS}_linux_amd64.zip"
      - unzip terraform_${TF_VERS}_linux_amd64.zip -d /usr/local/bin/
      - chmod +x /usr/local/bin/terraform
      - terraform --version
      - curl -sSL https://storage.yandexcloud.net/yandexcloud-yc/install.sh | bash -s -- -i /usr/local -n
      - export PATH=$PATH:/usr/local/bin
  script: 
    - yc config set token ${YC_OATH_ID};
      yc config set folder-id ${TF_VAR_folder_id}
    - envsubst < ./repo/createbucket.sh | bash
  artifacts:
    reports:
      dotenv: auth.env
    expire_in: 30 minutes
    access: 'none' #через вебку не будет виден токен. Передача только между пайплайнами
  needs:
    - release-frontend-docker-image
terraforming:
  image: alpine:3.18
  stage: create-machine
  before_script:
      - apk add bash curl unzip envsubst unzip jq
      - curl -LO "https://hashicorp-releases.yandexcloud.net/terraform/${TF_VERS}/terraform_${TF_VERS}_linux_amd64.zip"
      - unzip terraform_${TF_VERS}_linux_amd64.zip -d /usr/local/bin/
      - chmod +x /usr/local/bin/terraform
      - terraform --version
      - curl -sSL https://storage.yandexcloud.net/yandexcloud-yc/install.sh | bash -s -- -i /usr/local -n
      - export PATH=$PATH:/usr/local/bin  
  script:
    - cd ./repo/terraform
    - >
      terraform init 
      -backend-config="access_key=${AWS_ACCESS_KEY_ID}"
      -backend-config="secret_key=${AWS_SECRET_ACCESS_KEY}"
      -backend-config="bucket=${TF_STATE_BUCKET}"
    - terraform show
    - terraform apply -auto-approve -var="vm_image_id=ubuntu-2204-lts"
    - echo "PUBLIC_IP=$(terraform output -json | jq -r '.public_address.value')" > $CI_PROJECT_DIR/terraform.env
  needs:
    - create-auth-and-bucket  
  artifacts:
    reports:
      dotenv: "terraform.env"

connect-to-machine:
  stage: connect-to-machine
  image: alpine:3.18
  needs: 
    - terraforming
    - generate-version
  before_script:
    - apk add --no-cache openssh-client ansible envsubst
    - eval $(ssh-agent -s)  
    - echo "$SSH_ID_RSA" | base64 -d |  tr -d '\r' | ssh-add -  
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan -H "$PUBLIC_IP" > ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - export ANSIBLE_CONFIG=$(pwd)/repo/ansible/ansible.cfg
  script:
    - ssh ansible@"$PUBLIC_IP" "echo 'Подключение успешно!!'"
    - envsubst < $(pwd)/repo/ansible/inventory/inventory.yml.tmpl > $(pwd)/repo/ansible/inventory/inventory.yml
    - envsubst < $(pwd)/repo/ansible/group_vars/all.yml.tmpl > $(pwd)/repo/ansible/group_vars/all.yml
    - ansible-playbook ./repo/ansible/ansible-playbook.yml
      --tags all-check,frontend
      -i $(pwd)/repo/ansible/inventory/inventory.yml 
      -e "registry_image_frontend=${CI_REGISTRY_IMAGE}/${APP_NAME}:${VERSION}"
      -e "@repo/ansible/group_vars/all.yml" 
    - ssh ansible@"$PUBLIC_IP" "docker ps"