- name: check install docker
  command: which docker
  register: docker_check
  ignore_errors: true
  changed_when: false

### проверяем наличие контейнеров и записываем в переменную existing_containers ###
- name: Detect existing containers
  command: docker ps -a --format "{{ '{{' }}.Names{{ '}}' }}"
  register: existing_containers
  when: docker_check.rc == 0
  changed_when: false

### Если есть контейнер green, то переменная будет blue ###
- name: Set colors for green to blue
  set_fact:
    new_color: "blue"
    old_color: "green"
  when:
    - docker_check.rc == 0
    - existing_containers is defined
    - "'pelmennaya-backend-green' in existing_containers.stdout"

### Если есть контейнер blue, то переменная будет green ###
- name: Set colors for blue -> green switch
  set_fact:
    new_color: "green"
    old_color: "blue"
  when:
    - docker_check.rc == 0
    - existing_containers is defined
    - "'pelmennaya-backend-blue' in existing_containers.stdout"
### Если вообще контейнеров нет - то устанавливаем от балды ###
- name: Set default color if no containers detected
  set_fact:
    new_color: "green"
    old_color: "none"
  when:
    - docker_check.rc == 0
    - existing_containers is defined
    - "'pelmennaya-backend-green' not in existing_containers.stdout"
    - "'pelmennaya-backend-blue' not in existing_containers.stdout"