{
 "title": "Дашборд Пельменной",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  { "title": "Бизнесс-виджеты", "type": "text", "gridPos": { "h": 1, "w": 8, "x": 0, "y": 0 } },
  { "title": "Сетевые виджеты", "type": "text", "gridPos": { "h": 1, "w": 6, "x": 9, "y": 0 } },
  { "title": "Статус ВМ", "type": "text", "gridPos": { "h": 1, "w": 8, "x": 16, "y": 0 } },
  {
   "title": "Заказы за 5 минут",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "targets": [
    { "expr": "rate(orders_count[5m])", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Кол-во заказов пельменей",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 1 },
   "targets": [
    { "expr": "orders_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Кол-во HTTP запросов (чек дудос)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 9, "y": 1 },
   "targets": [
    { "expr": "requests_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Бэкэнд Пельменной",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{instance=\"pelmennaya-backend-active:8081\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "99 перцентиль для /products",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(response_timing_ms_bucket{handler=\"/products/\"}[5m])) by (le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "99 перцентиль для /categories",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 6 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(response_timing_ms_bucket{handler=\"/categories/\"}[5m])) by (le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "New panel",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (avg by(instance, cpu) (rate(node_cpu_seconds_total{mode=\"idle\"}[1m])) * 100)",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n  (node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) \n  / \n  node_memory_MemTotal_bytes\n) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n  (node_memory_SwapTotal_bytes - node_memory_SwapFree_bytes)\n  /\n  node_memory_SwapTotal_bytes\n) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Среднее время по всем API",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum(rate(response_timing_ms_sum[5m])) by (handler) / sum(rate(response_timing_ms_count[5m])) by (handler)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Входящий трафик (КБ\\сек)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 13 },
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{device!~\"lo|bond[0-9]|cbr[0-9]|veth.*\"}[1m]) / 1024",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Исходящий трафик (КБ\\сек)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 13 },
   "targets": [
    {
     "expr": "rate(node_network_transmit_bytes_total{device!~\"lo|bond[0-9]|cbr[0-9]|veth.*\"}[1m]) / 1024",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}