---
    - name: update apt cache
      ansible.builtin.apt:
        update_cache: yes
      become: true

    - name: install ca-certificates and curl
      ansible.builtin.apt:
        name:
          - ca-certificates
          - curl
        state: present
      become: true

    - name: make sure keyrings directory exists
      ansible.builtin.file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0775'
      become: true

    - name: download docker gpg key
      ansible.builtin.get_url:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: /etc/apt/keyrings/docker.asc
      become: true

    - name: set permissions on downloaded gpg key
      ansible.builtin.file:
        path: /etc/apt/keyrings/docker.asc
        mode: '0644'
      become: true

    - name: add docker repository into sources list
      ansible.builtin.apt_repository:
        repo: deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
        filename: docker.list
      become: true

    - name: update apt cache
      ansible.builtin.apt:
        update_cache: yes
      become: true

    - name: install docker
      ansible.builtin.apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present
      become: true

    - name: install docker-compose
      ansible.builtin.get_url:
        url: https://github.com/docker/compose/releases/latest/download/docker-compose-Linux-x86_64
        dest: /usr/local/bin/docker-compose
        mode: '0755'
      become: true

    - name: give docker-compose executable permission
      ansible.builtin.file:
        path: /usr/local/bin/docker-compose
        mode: '0755'
      become: true

    # comment the two below tasks out if you want to use sudo with each docker command
    - name: create docker group
      ansible.builtin.group:
        name: docker
        state: present
      become: true

    - name: add user to docker group
      ansible.builtin.user:
        name: "{{ ansible_user_id }}"
        groups: docker
        append: yes
      become: true
        
    - name: Login to Docker registry
      docker_login:
        registry: "{{ registry_url }}"
        username: "{{ registry_user }}"
        password: "{{ registry_password }}"

    - name: Ensure Docker network exists
      community.docker.docker_network:
        name: "{{ docker_network }}"
        driver: bridge
        state: present 