---
#Версии образов
prometheus_version: "latest"
grafana_version: "latest"
node_exporter_version: "latest"

#Порты
prometheus_port: 9090
grafana_port: 3000
node_exporter_port: 9100
app_exporter_port: 8081  # Порт вашего Go-приложения

# Учетные данные Grafana
grafana_admin_user: "admin"
grafana_admin_password: "securepassword"

# Целевые хосты для мониторинга
monitored_hosts:
  - "localhost:{{ node_exporter_port }}"
  - "pelmennaya-backend-active:{{ app_exporter_port }}"  # Замените на hostname вашего Go-приложения